
[project]
name = "stormfusion"
version = "0.1.0"
description = "Small-to-large, simple-to-novel meteorology DL scaffold on SEVIR"
authors = [{name="StormFusion Team"}]
requires-python = ">=3.9"
dependencies = []

[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "I"]
